package Final;
/*******************************************
  Universidad del Valle de Guatemala
  Algoritmos y Estructura de Datos
  Autores:
  Juan Tzun         Carnet 13017
  Carlos Cordero    Carnet 13152
  Fecha: 08/05/2014
********************************************/
public class InterfazGrafica extends javax.swing.JFrame {

    /**
     * Creates new form InterfazGrafica
     */
    public InterfazGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        panel = new javax.swing.JPanel();
        lblCalculadora = new javax.swing.JLabel();
        lblPostFix = new javax.swing.JLabel();
        pnlMargen1 = new javax.swing.JPanel();
        pnlMargen3 = new javax.swing.JPanel();
        rdbArrayList = new javax.swing.JRadioButton();
        rdbVector = new javax.swing.JRadioButton();
        rdbList = new javax.swing.JRadioButton();
        rdbDoble = new javax.swing.JRadioButton();
        rdbSimple = new javax.swing.JRadioButton();
        rdbCircular = new javax.swing.JRadioButton();
        lblPila = new javax.swing.JLabel();
        lblLista = new javax.swing.JLabel();
        btnArchivo = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora PostFix");

        panel.setBackground(new java.awt.Color(255, 255, 255));

        lblCalculadora.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        lblCalculadora.setText("CALCULADORA");

        lblPostFix.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblPostFix.setText("(PostFix)");

        pnlMargen1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlMargen1Layout = new javax.swing.GroupLayout(pnlMargen1);
        pnlMargen1.setLayout(pnlMargen1Layout);
        pnlMargen1Layout.setHorizontalGroup(
            pnlMargen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlMargen1Layout.setVerticalGroup(
            pnlMargen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnlMargen3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlMargen3Layout = new javax.swing.GroupLayout(pnlMargen3);
        pnlMargen3.setLayout(pnlMargen3Layout);
        pnlMargen3Layout.setHorizontalGroup(
            pnlMargen3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlMargen3Layout.setVerticalGroup(
            pnlMargen3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        rdbArrayList.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdbArrayList);
        rdbArrayList.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        rdbArrayList.setForeground(new java.awt.Color(0, 0, 204));
        rdbArrayList.setText("ArrayList");
        rdbArrayList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbArrayListActionPerformed(evt);
            }
        });

        rdbVector.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdbVector);
        rdbVector.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        rdbVector.setForeground(new java.awt.Color(0, 0, 204));
        rdbVector.setText("Vector");
        rdbVector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbVectorActionPerformed(evt);
            }
        });

        rdbList.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdbList);
        rdbList.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        rdbList.setForeground(new java.awt.Color(0, 0, 204));
        rdbList.setText("List");
        rdbList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbListActionPerformed(evt);
            }
        });

        rdbDoble.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rdbDoble);
        rdbDoble.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        rdbDoble.setForeground(new java.awt.Color(204, 0, 0));
        rdbDoble.setText("Doble");
        rdbDoble.setEnabled(false);
        rdbDoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbDobleActionPerformed(evt);
            }
        });

        rdbSimple.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rdbSimple);
        rdbSimple.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        rdbSimple.setForeground(new java.awt.Color(204, 0, 0));
        rdbSimple.setText("Simple");
        rdbSimple.setEnabled(false);
        rdbSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbSimpleActionPerformed(evt);
            }
        });

        rdbCircular.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rdbCircular);
        rdbCircular.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        rdbCircular.setForeground(new java.awt.Color(204, 0, 0));
        rdbCircular.setText("Circular");
        rdbCircular.setEnabled(false);
        rdbCircular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCircularActionPerformed(evt);
            }
        });

        lblPila.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPila.setText("Tipo de Pila:");

        lblLista.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblLista.setText("Tipo de Lista:");

        btnArchivo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnArchivo.setText("Archivo...");
        btnArchivo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnArchivo.setEnabled(false);
        btnArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivoActionPerformed(evt);
            }
        });

        btnCalcular.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCalcular.setEnabled(false);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClear.setEnabled(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMargen1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMargen3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(lblCalculadora))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(lblPostFix)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblPila))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbVector)
                            .addComponent(rdbList)
                            .addComponent(rdbArrayList)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLista)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbSimple)
                            .addComponent(rdbCircular)
                            .addComponent(rdbDoble)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(btnArchivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(pnlMargen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPostFix)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlMargen3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPila)
                    .addComponent(lblLista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(rdbArrayList)
                        .addGap(18, 18, 18)
                        .addComponent(rdbVector)
                        .addGap(18, 18, 18)
                        .addComponent(rdbList))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(rdbSimple)
                        .addGap(18, 18, 18)
                        .addComponent(rdbDoble)
                        .addGap(18, 18, 18)
                        .addComponent(rdbCircular)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel.getAccessibleContext().setAccessibleName("");
        panel.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbListActionPerformed
        rdbSimple.setEnabled(true);
        rdbDoble.setEnabled(true);
        rdbCircular.setEnabled(true);
        rdbSimple.setSelected(false);
        rdbSimple.setSelected(false);
        rdbSimple.setSelected(false);
        btnArchivo.setEnabled(false);
    }//GEN-LAST:event_rdbListActionPerformed

    private void rdbVectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbVectorActionPerformed
        rdbSimple.setEnabled(false);
        rdbDoble.setEnabled(false);
        rdbCircular.setEnabled(false);
        rdbSimple.setSelected(false);
        rdbSimple.setSelected(false);
        rdbSimple.setSelected(false);
        btnArchivo.setEnabled(true);
    }//GEN-LAST:event_rdbVectorActionPerformed

    private void rdbArrayListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbArrayListActionPerformed
        rdbSimple.setEnabled(false);
        rdbDoble.setEnabled(false);
        rdbCircular.setEnabled(false);
        rdbSimple.setSelected(false);
        rdbSimple.setSelected(false);
        rdbSimple.setSelected(false);
        btnArchivo.setEnabled(true);
    }//GEN-LAST:event_rdbArrayListActionPerformed

    private void btnArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivoActionPerformed
        btnCalcular.setEnabled(true);
        rdbSimple.setEnabled(false);
        rdbDoble.setEnabled(false);
        rdbCircular.setEnabled(false);
        rdbVector.setEnabled(false);
        rdbList.setEnabled(false);
        rdbArrayList.setEnabled(false);
    }//GEN-LAST:event_btnArchivoActionPerformed

    private void rdbSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbSimpleActionPerformed
        btnArchivo.setEnabled(true);
    }//GEN-LAST:event_rdbSimpleActionPerformed

    private void rdbDobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbDobleActionPerformed
        btnArchivo.setEnabled(true);
    }//GEN-LAST:event_rdbDobleActionPerformed

    private void rdbCircularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCircularActionPerformed
        btnArchivo.setEnabled(true);
    }//GEN-LAST:event_rdbCircularActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        rdbArrayList.setEnabled(true);
        rdbVector.setEnabled(true);
        rdbList.setEnabled(true);
        btnArchivo.setEnabled(false);
        btnCalcular.setEnabled(false);
        btnClear.setEnabled(false);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        btnClear.setEnabled(true);
        btnCalcular.setEnabled(false);
        btnArchivo.setEnabled(false);
    }//GEN-LAST:event_btnCalcularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArchivo;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnClear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel lblCalculadora;
    private javax.swing.JLabel lblLista;
    private javax.swing.JLabel lblPila;
    private javax.swing.JLabel lblPostFix;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel pnlMargen1;
    private javax.swing.JPanel pnlMargen3;
    private javax.swing.JRadioButton rdbArrayList;
    private javax.swing.JRadioButton rdbCircular;
    private javax.swing.JRadioButton rdbDoble;
    private javax.swing.JRadioButton rdbList;
    private javax.swing.JRadioButton rdbSimple;
    private javax.swing.JRadioButton rdbVector;
    // End of variables declaration//GEN-END:variables
}
